require ('dotenv').config()
require('./config/passport.js')
const  express = require('express')
const path = require('path')
const cookieParser = require('cookie-parser')
const ConnectDB = require('./config/db_connection')
const checkUser = require('./middlewares/checkUser.js')
const passport = require('passport')
const app = express()
app.use(cookieParser())
ConnectDB()
app.use(passport.initialize())
app.use(checkUser)
app.use(express.json())
app.use(express.static(path.join(__dirname,'public')))
app.use(express.urlencoded({extended:true}))
app.set('view engine','ejs')

const mainPage = require('./routes/main-route')
const loginPage = require('./routes/login-route')
const sigupPage = require('./routes/signup-route')
const profilePage = require('./routes/profile-route')
const logoutPage = require('./routes/logout-route')
const deletePage = require('./routes/delete-route')
const statusPage = require('./routes/status-route')
const editPage = require('./routes/edit-route.js')
const updatePage = require('./routes/update-route.js')
const featurePage = require('./routes/feature-route.js')
const authPage = require('./routes/auth-route.js')

app.use('/', mainPage)
app.use('/auth',authPage)
app.use('/login', loginPage)
app.use('/signup' , sigupPage)
app.use('/logout' , logoutPage)
app.use('/profile' , profilePage)
app.use('/delete' , deletePage)
app.use('/status' , statusPage)
app.use('/edit' , editPage)
app.use('/update' , updatePage)
app.use('/features' , featurePage)

const PORT = process.env.PORT
app.listen(PORT,()=>{
    console.log(`Server Running on port ${PORT}`);
    
})